<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\D2G.Iris.ML\D2G.Iris.ML.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dialogs\" />
    <Folder Include="Styles\" />
    <Folder Include="Utilities\" />
    <Folder Include="Views\" />
  </ItemGroup>

</Project>
